import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
  decimal,
} from "drizzle-orm/pg-core";
import { user } from "./auth.schema";
import { callStatusEnum, paymentMethodEnum, videoStatusEnum } from "./enums";

export const calls = pgTable("calls", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  status: callStatusEnum("status").notNull().default("call_created"),
  recipientName: text("recipient_name").notNull(),
  recipientContext: text("recipient_context").notNull(), // max 1000 chars enforced in application
  script: text("script"), // Generated by OpenAI
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  firstAttemptAt: timestamp("first_attempt_at"), // When first call was attempted
  lastAttemptAt: timestamp("last_attempt_at"), // When last call was attempted
  daysSinceFirstAttempt: integer("days_since_first_attempt").default(0), // Days since first attempt
  nextRetryAt: timestamp("next_retry_at"), // When to attempt next call
  isFree: boolean("is_free").notNull().default(false),
  paymentMethod: paymentMethodEnum("payment_method").notNull(),
  paymentTxHash: text("payment_tx_hash"),
  paymentAmount: decimal("payment_amount", { precision: 18, scale: 8 }), // ZEC equivalent
  encryptedHandle: text("encrypted_handle"), // Fhenix encrypted PII
  callSid: text("call_sid"), // Twilio Call SID for webhook mapping
  recordingUrl: text("recording_url"), // Twilio recording URL
  recordingSid: text("recording_sid"), // Twilio recording SID
  duration: integer("duration"), // seconds
  videoUrl: text("video_url"), // S3 video URL
  videoStatus: videoStatusEnum("video_status").default("pending"),
  wavespeedJobId: text("wavespeed_job_id"), // WavespeedAI job IDs (comma-separated)
  videoErrorMessage: text("video_error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

