import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
  decimal,
} from "drizzle-orm/pg-core";
import { user } from "./auth.schema";
import { callStatusEnum, paymentMethodEnum, videoStatusEnum } from "./enums";

export const calls = pgTable("calls", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  status: callStatusEnum("status").notNull().default("call_created"),
  recipientName: text("recipient_name").notNull(),
  recipientContext: text("recipient_context").notNull(), // max 1000 chars enforced in application
  script: text("script"), // Generated by OpenAI
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  isFree: boolean("is_free").notNull().default(false),
  paymentMethod: paymentMethodEnum("payment_method").notNull(),
  paymentTxHash: text("payment_tx_hash"),
  paymentAmount: decimal("payment_amount", { precision: 18, scale: 8 }), // ZEC equivalent
  encryptedHandle: text("encrypted_handle"), // Fhenix encrypted PII
  recordingUrl: text("recording_url"), // Twilio recording URL
  recordingSid: text("recording_sid"), // Twilio recording SID
  duration: integer("duration"), // seconds
  videoUrl: text("video_url"), // S3 video URL
  videoStatus: videoStatusEnum("video_status").default("pending"),
  falJobId: text("fal_job_id"),
  videoErrorMessage: text("video_error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

