import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
  decimal,
} from "drizzle-orm/pg-core";
import { user } from "./auth.schema";
import { callStatusEnum, paymentMethodEnum, videoStatusEnum } from "./enums";

export const calls = pgTable("calls", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  status: callStatusEnum("status").notNull().default("call_created"),
  recipientName: text("recipient_name").notNull(),
  anythingElse: text("anything_else"), // Optional additional context
  // Target person details for personalization
  targetGender: text("target_gender").notNull(), // "male", "female", "prefer_not_to_say", or "other"
  targetGenderCustom: text("target_gender_custom"), // Custom gender if "other" selected
  targetAgeRange: text("target_age_range"), // "18-25", "26-35", "36-45", "46-55", "56+"
  targetPhysicalDescription: text("target_physical_description"), // Hair, clothing, etc.
  // New fields for better personalization
  targetCity: text("target_city"), // City/area they live in
  targetHobby: text("target_hobby"), // Their hobby or interest
  targetProfession: text("target_profession"), // Their job/profession
  interestingPiece: text("interesting_piece"), // "One thing virtually no one knows about them"
  ragebaitTrigger: text("ragebait_trigger"), // "If you wanted to ragebait them, you would say this"
  videoStyle: text("video_style"), // Aesthetic style: "anime", "claymation", "puppets", etc.
  // Optional uploaded image for video generation
  uploadedImageUrl: text("uploaded_image_url"), // S3 URL of user-uploaded image
  uploadedImageS3Key: text("uploaded_image_s3_key"), // S3 key for uploaded image
  // Generated prompts
  openaiPrompt: text("openai_prompt"), // Generated OpenAI call instructions
  imagePrompt: text("image_prompt"), // Generated image generation prompt
  script: text("script"), // Generated by OpenAI
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  firstAttemptAt: timestamp("first_attempt_at"), // When first call was attempted
  lastAttemptAt: timestamp("last_attempt_at"), // When last call was attempted
  daysSinceFirstAttempt: integer("days_since_first_attempt").default(0), // Days since first attempt
  nextRetryAt: timestamp("next_retry_at"), // When to attempt next call
  isFree: boolean("is_free").notNull().default(false),
  paymentMethod: paymentMethodEnum("payment_method").notNull(),
  paymentTxHash: text("payment_tx_hash"),
  paymentAmount: decimal("payment_amount", { precision: 18, scale: 8 }), // ZEC equivalent
  encryptedHandle: text("encrypted_handle"), // Legacy encrypted PII (deprecated)
  // Fhenix FHE encryption fields
  fhenixEnabled: boolean("fhenix_enabled").notNull().default(false), // Whether FHE encryption is used
  fhenixVaultId: text("fhenix_vault_id"), // bytes32 callId in PIIVault contract on Base
  callSid: text("call_sid"), // Twilio Call SID for webhook mapping
  recordingUrl: text("recording_url"), // Twilio recording URL
  recordingSid: text("recording_sid"), // Twilio recording SID
  duration: integer("duration"), // seconds
  videoUrl: text("video_url"), // S3 video URL (may be expired presigned URL)
  videoS3Key: text("video_s3_key"), // S3 object key for generating fresh URLs
  videoStatus: videoStatusEnum("video_status").default("pending"),
  wavespeedJobId: text("wavespeed_job_id"), // WavespeedAI job IDs (comma-separated)
  videoErrorMessage: text("video_error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

