/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YourCallsRouteImport } from './routes/your-calls'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallersSlugRouteImport } from './routes/callers.$slug'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiCallersRouteImport } from './routes/api/callers'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as ApiZcashPaymentRouteImport } from './routes/api/zcash/payment'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload/image'
import { Route as ApiTwilioVoiceRouteImport } from './routes/api/twilio/voice'
import { Route as ApiTestCallSimpleRouteImport } from './routes/api/test/call-simple'
import { Route as ApiTestCallRouteImport } from './routes/api/test/call'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStarknetPaymentRouteImport } from './routes/api/starknet/payment'
import { Route as ApiNearAiChatRouteImport } from './routes/api/near-ai/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksTwilioRecordingStatusRouteImport } from './routes/api/webhooks/twilio/recording-status'
import { Route as ApiWebhooksTwilioConversationRelayCompleteRouteImport } from './routes/api/webhooks/twilio/conversation-relay-complete'
import { Route as ApiWebhooksTwilioCallStatusRouteImport } from './routes/api/webhooks/twilio/call-status'

const YourCallsRoute = YourCallsRouteImport.update({
  id: '/your-calls',
  path: '/your-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallersSlugRoute = CallersSlugRouteImport.update({
  id: '/callers/$slug',
  path: '/callers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallersRoute = ApiCallersRouteImport.update({
  id: '/api/callers',
  path: '/api/callers',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const ApiZcashPaymentRoute = ApiZcashPaymentRouteImport.update({
  id: '/api/zcash/payment',
  path: '/api/zcash/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceRoute = ApiTwilioVoiceRouteImport.update({
  id: '/api/twilio/voice',
  path: '/api/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCallSimpleRoute = ApiTestCallSimpleRouteImport.update({
  id: '/api/test/call-simple',
  path: '/api/test/call-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCallRoute = ApiTestCallRouteImport.update({
  id: '/api/test/call',
  path: '/api/test/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStarknetPaymentRoute = ApiStarknetPaymentRouteImport.update({
  id: '/api/starknet/payment',
  path: '/api/starknet/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearAiChatRoute = ApiNearAiChatRouteImport.update({
  id: '/api/near-ai/chat',
  path: '/api/near-ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTwilioRecordingStatusRoute =
  ApiWebhooksTwilioRecordingStatusRouteImport.update({
    id: '/api/webhooks/twilio/recording-status',
    path: '/api/webhooks/twilio/recording-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksTwilioConversationRelayCompleteRoute =
  ApiWebhooksTwilioConversationRelayCompleteRouteImport.update({
    id: '/api/webhooks/twilio/conversation-relay-complete',
    path: '/api/webhooks/twilio/conversation-relay-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksTwilioCallStatusRoute =
  ApiWebhooksTwilioCallStatusRouteImport.update({
    id: '/api/webhooks/twilio/call-status',
    path: '/api/webhooks/twilio/call-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/your-calls': typeof YourCallsRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/api/callers': typeof ApiCallersRoute
  '/api/config': typeof ApiConfigRoute
  '/callers/$slug': typeof CallersSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/near-ai/chat': typeof ApiNearAiChatRoute
  '/api/starknet/payment': typeof ApiStarknetPaymentRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/test/call': typeof ApiTestCallRoute
  '/api/test/call-simple': typeof ApiTestCallSimpleRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/zcash/payment': typeof ApiZcashPaymentRoute
  '/api/webhooks/twilio/call-status': typeof ApiWebhooksTwilioCallStatusRoute
  '/api/webhooks/twilio/conversation-relay-complete': typeof ApiWebhooksTwilioConversationRelayCompleteRoute
  '/api/webhooks/twilio/recording-status': typeof ApiWebhooksTwilioRecordingStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/your-calls': typeof YourCallsRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/api/callers': typeof ApiCallersRoute
  '/api/config': typeof ApiConfigRoute
  '/callers/$slug': typeof CallersSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/near-ai/chat': typeof ApiNearAiChatRoute
  '/api/starknet/payment': typeof ApiStarknetPaymentRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/test/call': typeof ApiTestCallRoute
  '/api/test/call-simple': typeof ApiTestCallSimpleRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/zcash/payment': typeof ApiZcashPaymentRoute
  '/api/webhooks/twilio/call-status': typeof ApiWebhooksTwilioCallStatusRoute
  '/api/webhooks/twilio/conversation-relay-complete': typeof ApiWebhooksTwilioConversationRelayCompleteRoute
  '/api/webhooks/twilio/recording-status': typeof ApiWebhooksTwilioRecordingStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRoute
  '/calls': typeof CallsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/your-calls': typeof YourCallsRoute
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/api/callers': typeof ApiCallersRoute
  '/api/config': typeof ApiConfigRoute
  '/callers/$slug': typeof CallersSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/near-ai/chat': typeof ApiNearAiChatRoute
  '/api/starknet/payment': typeof ApiStarknetPaymentRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/test/call': typeof ApiTestCallRoute
  '/api/test/call-simple': typeof ApiTestCallSimpleRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/zcash/payment': typeof ApiZcashPaymentRoute
  '/api/webhooks/twilio/call-status': typeof ApiWebhooksTwilioCallStatusRoute
  '/api/webhooks/twilio/conversation-relay-complete': typeof ApiWebhooksTwilioConversationRelayCompleteRoute
  '/api/webhooks/twilio/recording-status': typeof ApiWebhooksTwilioRecordingStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calls'
    | '/create'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/your-calls'
    | '/login'
    | '/signup'
    | '/api/callers'
    | '/api/config'
    | '/callers/$slug'
    | '/api/auth/$'
    | '/api/near-ai/chat'
    | '/api/starknet/payment'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/test/call'
    | '/api/test/call-simple'
    | '/api/twilio/voice'
    | '/api/upload/image'
    | '/api/zcash/payment'
    | '/api/webhooks/twilio/call-status'
    | '/api/webhooks/twilio/conversation-relay-complete'
    | '/api/webhooks/twilio/recording-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calls'
    | '/create'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/your-calls'
    | '/login'
    | '/signup'
    | '/api/callers'
    | '/api/config'
    | '/callers/$slug'
    | '/api/auth/$'
    | '/api/near-ai/chat'
    | '/api/starknet/payment'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/test/call'
    | '/api/test/call-simple'
    | '/api/twilio/voice'
    | '/api/upload/image'
    | '/api/zcash/payment'
    | '/api/webhooks/twilio/call-status'
    | '/api/webhooks/twilio/conversation-relay-complete'
    | '/api/webhooks/twilio/recording-status'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/calls'
    | '/create'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/your-calls'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/api/callers'
    | '/api/config'
    | '/callers/$slug'
    | '/api/auth/$'
    | '/api/near-ai/chat'
    | '/api/starknet/payment'
    | '/api/stripe/checkout'
    | '/api/stripe/webhook'
    | '/api/test/call'
    | '/api/test/call-simple'
    | '/api/twilio/voice'
    | '/api/upload/image'
    | '/api/zcash/payment'
    | '/api/webhooks/twilio/call-status'
    | '/api/webhooks/twilio/conversation-relay-complete'
    | '/api/webhooks/twilio/recording-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRoute
  CallsRoute: typeof CallsRoute
  CreateRoute: typeof CreateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  YourCallsRoute: typeof YourCallsRoute
  ApiCallersRoute: typeof ApiCallersRoute
  ApiConfigRoute: typeof ApiConfigRoute
  CallersSlugRoute: typeof CallersSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNearAiChatRoute: typeof ApiNearAiChatRoute
  ApiStarknetPaymentRoute: typeof ApiStarknetPaymentRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTestCallRoute: typeof ApiTestCallRoute
  ApiTestCallSimpleRoute: typeof ApiTestCallSimpleRoute
  ApiTwilioVoiceRoute: typeof ApiTwilioVoiceRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiZcashPaymentRoute: typeof ApiZcashPaymentRoute
  ApiWebhooksTwilioCallStatusRoute: typeof ApiWebhooksTwilioCallStatusRoute
  ApiWebhooksTwilioConversationRelayCompleteRoute: typeof ApiWebhooksTwilioConversationRelayCompleteRoute
  ApiWebhooksTwilioRecordingStatusRoute: typeof ApiWebhooksTwilioRecordingStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/your-calls': {
      id: '/your-calls'
      path: '/your-calls'
      fullPath: '/your-calls'
      preLoaderRoute: typeof YourCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callers/$slug': {
      id: '/callers/$slug'
      path: '/callers/$slug'
      fullPath: '/callers/$slug'
      preLoaderRoute: typeof CallersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callers': {
      id: '/api/callers'
      path: '/api/callers'
      fullPath: '/api/callers'
      preLoaderRoute: typeof ApiCallersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/api/zcash/payment': {
      id: '/api/zcash/payment'
      path: '/api/zcash/payment'
      fullPath: '/api/zcash/payment'
      preLoaderRoute: typeof ApiZcashPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice': {
      id: '/api/twilio/voice'
      path: '/api/twilio/voice'
      fullPath: '/api/twilio/voice'
      preLoaderRoute: typeof ApiTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/call-simple': {
      id: '/api/test/call-simple'
      path: '/api/test/call-simple'
      fullPath: '/api/test/call-simple'
      preLoaderRoute: typeof ApiTestCallSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/call': {
      id: '/api/test/call'
      path: '/api/test/call'
      fullPath: '/api/test/call'
      preLoaderRoute: typeof ApiTestCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/starknet/payment': {
      id: '/api/starknet/payment'
      path: '/api/starknet/payment'
      fullPath: '/api/starknet/payment'
      preLoaderRoute: typeof ApiStarknetPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/near-ai/chat': {
      id: '/api/near-ai/chat'
      path: '/api/near-ai/chat'
      fullPath: '/api/near-ai/chat'
      preLoaderRoute: typeof ApiNearAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio/recording-status': {
      id: '/api/webhooks/twilio/recording-status'
      path: '/api/webhooks/twilio/recording-status'
      fullPath: '/api/webhooks/twilio/recording-status'
      preLoaderRoute: typeof ApiWebhooksTwilioRecordingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio/conversation-relay-complete': {
      id: '/api/webhooks/twilio/conversation-relay-complete'
      path: '/api/webhooks/twilio/conversation-relay-complete'
      fullPath: '/api/webhooks/twilio/conversation-relay-complete'
      preLoaderRoute: typeof ApiWebhooksTwilioConversationRelayCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio/call-status': {
      id: '/api/webhooks/twilio/call-status'
      path: '/api/webhooks/twilio/call-status'
      fullPath: '/api/webhooks/twilio/call-status'
      preLoaderRoute: typeof ApiWebhooksTwilioCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRoute,
  CallsRoute: CallsRoute,
  CreateRoute: CreateRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  YourCallsRoute: YourCallsRoute,
  ApiCallersRoute: ApiCallersRoute,
  ApiConfigRoute: ApiConfigRoute,
  CallersSlugRoute: CallersSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNearAiChatRoute: ApiNearAiChatRoute,
  ApiStarknetPaymentRoute: ApiStarknetPaymentRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTestCallRoute: ApiTestCallRoute,
  ApiTestCallSimpleRoute: ApiTestCallSimpleRoute,
  ApiTwilioVoiceRoute: ApiTwilioVoiceRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiZcashPaymentRoute: ApiZcashPaymentRoute,
  ApiWebhooksTwilioCallStatusRoute: ApiWebhooksTwilioCallStatusRoute,
  ApiWebhooksTwilioConversationRelayCompleteRoute:
    ApiWebhooksTwilioConversationRelayCompleteRoute,
  ApiWebhooksTwilioRecordingStatusRoute: ApiWebhooksTwilioRecordingStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
